### ISSUE TITLE
useDebugValue?

### ISSUE THREAD

**Issue by fritx** [kingback/react-polyfills#1]
useDebugValue
https://reactjs.org/docs/hooks-reference.html#usedebugvalue

Thanks for this awesome library :+1:

**Comment by kingback** [comment]
`useDebugValue` is used for React DevTools, but the hooks polyfill doesn't work in React DevTools, so I just export `useDebugValue` as an empty function.

```js
import { useDebugValue } from 'react-polyfill-hooks';

function useCustomHook() {
  const [value] = useState(0);
  useDebugValue(value); // do nothing
  return value;
}
```
